[[redirects]]
  from = "/rich-destiny/login/*"
  to = "http://localhost:35893/callback?code=:code&state=:state"
  query = {code = ":code", state = ":state"}

[[redirects]]
  from = "/membercount"
  to = "https://membercount.net"

[[redirects]]
  from = "/gms/bungie/redirect"
  to = "http://localhost:1234/bungie/redirect?code=:code&state=:state"
  query = {code = ":code", state = ":state"}